version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - scrapy_mysql_net
    command: ["python", "app.py"]

  scraper:
    build: ./scraper
    container_name: scraper
    # ports:
    #  - "5000:5000"
    networks:
      - scrapy_mysql_net
    command: ["wait-for-it", "mysql:3306", "--timeout=10","--","scrapy", "crawl", "fvs"]

  db:
    image: mysql
    container_name: db
    command: ["--init-file=/tmp/mysql-init.sql"]
    restart: always
    environment:
      MYSQL_NATIVE_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
      MYSQL_USER: 'scraper'
    volumes:
      - ./db/db_dir:/var/lib/mysql
      - ./db/mysql-init.sql:/tmp/mysql-init.sql
      # new commented line
    networks:
      - scrapy_mysql_net
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  db_dir:

networks:
  scrapy_mysql_net:
